GOOGLE_API_KEY="AIzaSyBUDTq7vDGf2u1irIxLw6UysiGRJXFx9ZY"
GOOGLE_API_KEY1="AIzaSyBDFt-5bgYYtp14RNSH41dA-ONbgEP-AaQ"
GOOGLE_API_KEY2="AIzaSyAJXVGUwtI8m5LxtgMhCHsJxgzeQmEFEmE"
GOOGLE_API_KEY3="AIzaSyDXTIc3Jc9AMO2vzsa6i9k0SUuqhqAmoQ0"

PINECONE_API_KEY="pcsk_4ZB9ey_Ce2Rz3sh9NunsuQFhdWqCd6dzh5HERQUyNqDRHB5jPcJtRhGrmRVxwrdmBVN7KR"
PINECONE_ENVIRONMENT="us-east-1"

INDEX_NAME="jumaiddi"