GOOGLE_API_KEY="AIzaSyBYkV5z7kXj2CFPe3YWSliqUxMFOXHgR5U"
GOOGLE_API_KEY1="AIzaSyCHDCFtRVCAL0fvCW2th8ehahnI-GHsxf0"
GOOGLE_API_KEY2="AIzaSyCfHSOsAoDvE_CZq1h0e7G8T4n8VvuYzsg"

PINECONE_API_KEY="pcsk_4ZB9ey_Ce2Rz3sh9NunsuQFhdWqCd6dzh5HERQUyNqDRHB5jPcJtRhGrmRVxwrdmBVN7KR"
PINECONE_ENVIRONMENT="us-east-1"

INDEX_NAME="jumaiddi"