GOOGLE_API_KEY="AIzaSyAfyvIpky6ispcPwbohQVd1RKl2Dpv-59I"
GOOGLE_API_KEY1="AIzaSyArL2naBEUelXQ6m7qFr2pPB9vJYqbBJFM"
GOOGLE_API_KEY2="AIzaSyAGiwtZaf17-tuwucnd33uOJzu--2O-RaM"
GOOGLE_API_KEY3="AIzaSyA0whLvAWVjd7GARNIQ4NwpNAdcRlDMYfE"
GOOGLE_API_KEY4="AIzaSyCvgUFRpcJrFmMUhsyE-5of8SMqCXtzrSE"

PINECONE_API_KEY="pcsk_4ZB9ey_Ce2Rz3sh9NunsuQFhdWqCd6dzh5HERQUyNqDRHB5jPcJtRhGrmRVxwrdmBVN7KR"
PINECONE_ENVIRONMENT="us-east-1"

INDEX_NAME="jumaiddi"